# Path to zsh config folder
export ZSH=$HOME/.zsh

# Source my dotfiles (in explicit order, though my current config doesn't
# really require explicit ordering)
typeset -a DOTFILES
DOTFILES=(
    colors
    exports
    options
    aliases
    functions
    directories
    ssh
    git
    python
    history
    key-bindings
    platform
    prompt
    ruby
)
for file in $DOTFILES; do
    file=$ZSH/includes/$file
    [[ -f $file ]] && source $file
done
